FROM node:16.17.1-alpine
WORKDIR /lordsandlands

RUN mkdir -p /lordsandlands/api

RUN npm install -g pnpm && pnpm config set --global store-dir /root/.local/share/pnpm/store/v3

COPY ./api /lordsandlands/api
RUN cd api && pnpm install

WORKDIR /lordsandlands/api
CMD [ "pnpm", "run", "dev" ]