FROM node:16.17.1-alpine as base
WORKDIR /lordsandlands

RUN mkdir -p /lordsandlands/web
RUN mkdir -p /lordsandlands/api

RUN npm install -g pnpm && pnpm config set --global store-dir /root/.local/share/pnpm/store/v3

WORKDIR /lordsandlands/web

COPY ./web /lordsandlands/web
COPY ./api /lordsandlands/api
RUN cd /lordsandlands && pnpm install -r

#RUN pnpm test
RUN pnpm build